#!/usr/bin/env python3
"""
claudestate-hook.py
───────────────────
Claude Code session hook — drop this into your project root or
register it as a pre-tool-use hook in ~/.claude/settings.json.

It auto-injects the STATE.md summary into the context window
every time a Claude Code session starts, so Claude *always*
knows where it left off — zero manual effort.

Usage (standalone test):
    python3 claudestate-hook.py

Usage (Claude Code hook — settings.json):
    {
      "hooks": {
        "PreToolUse": [
          {
            "matcher": "",
            "hooks": [
              {
                "type": "command",
                "command": "python3 /path/to/claudestate-hook.py"
              }
            ]
          }
        ]
      }
    }
"""

from __future__ import annotations

import json
import os
import re
import subprocess
import sys
from datetime import datetime
from pathlib import Path

# ── config ────────────────────────────────────────────────────────────────────

STATE_FILE   = "STATE.md"
CLAUDE_FILE  = "CLAUDE.md"
MAX_TASKS    = 12        # cap checklist lines injected into context
HOOK_VERSION = "0.1.0"

# ── helpers ───────────────────────────────────────────────────────────────────

def find_state(start: Path) -> Path | None:
    """Walk up directory tree to find STATE.md (works in monorepos)."""
    for parent in [start, *start.parents]:
        candidate = parent / STATE_FILE
        if candidate.exists():
            return candidate
        # stop at git root
        if (parent / ".git").exists():
            break
    return None


def parse_tasks(md: str) -> list[dict]:
    tasks = []
    for line in md.splitlines():
        m = re.match(r"^\s*-\s+\[( |x)\]\s+(.+)$", line, re.IGNORECASE)
        if m:
            tasks.append({"done": m.group(1).lower() == "x", "text": m.group(2).strip()})
    return tasks


def git_branch(root: Path) -> str:
    try:
        r = subprocess.run(
            ["git", "rev-parse", "--abbrev-ref", "HEAD"],
            cwd=root, capture_output=True, text=True, timeout=3,
        )
        return r.stdout.strip() if r.returncode == 0 else "unknown"
    except Exception:
        return "unknown"


def git_last_commit(root: Path) -> str:
    try:
        r = subprocess.run(
            ["git", "log", "-1", "--pretty=format:%s (%cr)"],
            cwd=root, capture_output=True, text=True, timeout=3,
        )
        return r.stdout.strip() if r.returncode == 0 else ""
    except Exception:
        return ""


def extract_section(md: str, heading: str) -> str:
    pattern = rf"^## {re.escape(heading)}\s*$(.*?)(?=^## |\Z)"
    m = re.search(pattern, md, re.MULTILINE | re.DOTALL)
    return m.group(1).strip() if m else ""


# ── main injection ─────────────────────────────────────────────────────────────

def build_context_block(state_path: Path) -> str:
    """
    Build the compact context string that gets written to CLAUDE.md.
    Claude Code reads this at session start — keeps it under ~400 tokens.
    """
    root   = state_path.parent
    md     = state_path.read_text(encoding="utf-8")
    tasks  = parse_tasks(md)
    done   = sum(1 for t in tasks if t["done"])
    total  = len(tasks)
    pct    = int(done / total * 100) if total else 0

    # next open tasks (cap at 3 for brevity)
    next_tasks = [t["text"] for t in tasks if not t["done"]][:3]

    # blockers
    blockers_raw = extract_section(md, "Blockers")
    has_blockers = bool(blockers_raw) and "(none)" not in blockers_raw.lower()

    # git context
    branch      = git_branch(root)
    last_commit = git_last_commit(root)

    lines = [
        "<!-- AUTO-GENERATED by claudestate-hook — do not edit manually -->",
        "",
        "# ClaudeState — Session Context",
        "",
        f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        f"**Branch:** `{branch}`",
        f"**Progress:** {done}/{total} tasks ({pct}%)",
        "",
        "## Start Here",
        "",
    ]

    if next_tasks:
        for t in next_tasks:
            lines.append(f"- [ ] {t}")
    else:
        lines.append("All tasks complete — consider starting the next phase.")

    if has_blockers:
        lines += [
            "",
            "## Active Blockers",
            "",
            blockers_raw,
        ]

    if last_commit:
        lines += [
            "",
            f"**Last commit:** {last_commit}",
        ]

    # checklist snapshot (capped)
    checklist_lines = [
        l for l in md.splitlines()
        if re.match(r"^\s*-\s+\[", l)
    ][:MAX_TASKS]

    if checklist_lines:
        lines += [
            "",
            "## Task Snapshot",
            "",
            "```",
            *checklist_lines,
            "```",
        ]

    lines += [
        "",
        "---",
        f"*Full plan: `{STATE_FILE}` · Updated by: `claudestate checkpoint`*",
    ]

    return "\n".join(lines)


def run_hook() -> dict:
    """
    Entry point called by Claude Code hook system.
    Returns a JSON-serialisable result dict.
    """
    cwd        = Path.cwd()
    state_path = find_state(cwd)

    if not state_path:
        # No STATE.md — silently exit (project not using ClaudeState)
        return {"claudestate": False}

    try:
        block = build_context_block(state_path)
        claude_md = state_path.parent / CLAUDE_FILE
        claude_md.write_text(block, encoding="utf-8")

        tasks     = parse_tasks(state_path.read_text())
        done      = sum(1 for t in tasks if t["done"])
        next_task = next((t["text"] for t in tasks if not t["done"]), "All done!")

        result = {
            "claudestate": True,
            "state_file":  str(state_path),
            "tasks_done":  done,
            "tasks_total": len(tasks),
            "next_task":   next_task,
            "claude_md":   str(claude_md),
        }

        # Print human-readable summary to stderr (visible in Claude Code logs)
        print(
            f"[claudestate] context loaded — {done}/{len(tasks)} tasks · "
            f"Next: {next_task[:60]}",
            file=sys.stderr,
        )

        return result

    except Exception as exc:
        print(f"[claudestate] hook error: {exc}", file=sys.stderr)
        return {"claudestate": False, "error": str(exc)}


# ── Claude Code hook protocol ─────────────────────────────────────────────────
# Claude Code passes hook input via stdin as JSON and reads stdout as JSON.

if __name__ == "__main__":
    # Read optional hook input from Claude Code (ignored if not present)
    try:
        _input = json.loads(sys.stdin.read()) if not sys.stdin.isatty() else {}
    except Exception:
        _input = {}

    result = run_hook()

    # Output JSON for Claude Code hook protocol
    print(json.dumps(result))
